import Dynamic from "next/dynamic";
import Navbar from "@/my_components/Navbar/Navbar";
import { cookies, headers } from "next/headers";
import axios from "axios";
import DashboardProvider from "@/my_components/providers/DashboardProvider";

const RightSideNavbar = Dynamic(
  () => import("@/my_components/Navbar/RightSideNavbar")
);

const ChatSheetComponent = Dynamic(
  () => import("@/components/ChatSheetComponent")
);

export const metadata = {
  title: "XYZ | Dashboard",
  description: "Generated by Next.js",
};

async function getCookieData() {
  const cookieData = cookies().get("access_token");
  return new Promise((resolve) => resolve(cookieData));
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let dashboardInfo: any;
  try {
    const host = headers().get("host");
    const cookieStore = cookies();
    const access_token: any = await getCookieData();
    const { data } = await axios.get(`http://${host}/api/v1/dashboard`, {
      headers: {
        Cookie: `${access_token?.name}=${access_token?.value}`,
      },
    });
    if (data.success) {
      dashboardInfo = data.data;
    }
  } catch (err: any) {
    console.log(err);
  }

  if (!dashboardInfo) {
    return null;
  }

  if (dashboardInfo?.ChurchInfo?.length && dashboardInfo.role === "admin") {
    return <RightSideNavbar ChurchInfo={dashboardInfo.ChurchInfo} />;
  }

  return (
    <DashboardProvider
      UnseenChatCount={dashboardInfo.UnseenChatCount}
      recentJoined={dashboardInfo.PeopleCount}
      Events={dashboardInfo.Events}
      UserInfo={{
        _id: dashboardInfo._id,
        name: dashboardInfo.name,
        imageUrl: dashboardInfo.image,
        role: dashboardInfo.role,
      }}
      PaymentAmount={dashboardInfo.Payment}
    >
      <Navbar
        userInfo={{
          name: dashboardInfo.name,
          imageUrl: dashboardInfo.image,
          role: dashboardInfo.role,
        }}
      />
      {dashboardInfo.role === "people" && <ChatSheetComponent role="people" />}
      <div className="px-2 md:px-4 max-w-7xl mx-auto min-h-dvh">{children}</div>
    </DashboardProvider>
  );
}
